logging:
  level:
    com.hellowork.jobsoffer: DEBUG

spring:
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/jobsdb}

pole:
  emploi:
    api-base: ${POLE_EMPLOI_API_BASE:https://api.francetravail.io/partenaire}
    token-base: ${POLE_EMPLOI_AUTH_BASE:https://entreprise.pole-emploi.fr}
    client-id: ${POLE_EMPLOI_CLIENT_ID:}
    client-secret: ${POLE_EMPLOI_CLIENT_SECRET:}
    scope: ${POLE_EMPLOI_SCOPE:api_offresdemploiv2 o2dsoffre}
    page-size: ${POLE_EMPLOI_PAGE_SIZE:10}